### ISSUE TITLE
Designing wireframes for the website

### ISSUE THREAD

**Issue by sudhansubhushanmishra** [JapanTechAndLanguage/jap-english-tech-worddeck#8]
In my opinion, I feel we should plan and build a wireframe of how we would layout and design the webpage interface. I'll be working on it soon.

Thank you

**Comment by avie-dev** [comment]
Thank you @the-lazy-learner!
 We finalized the Wireframes [here](https://docs.google.com/document/d/1jQC-1_pSFbhzoX5Y9RQ_X-YQvzs5dD0RjfG8Dkp9Kv8/edit#heading=h.djgsom1iw0l8), do let me close this issue.

**Comment by sudhansubhushanmishra** [comment]
Closing the issue
